### ISSUE TITLE
Installing NuGet package fails on VSCode 1.71.2

### ISSUE THREAD

**Issue by mickut** [plbonneville/RazorInteractive#160]
Invoking the `#r "nuget:RazorInteractive"` fails consistently:
```
Error: Microsoft.DotNet.Interactive.KernelExtensionLoadException: Failure loading Kernel Extension
 ---> System.MissingMethodException: Method not found: 'Void Microsoft.DotNet.Interactive.CompositeKernel.Add(Microsoft.DotNet.Interactive.Kernel, System.Collections.Generic.IReadOnlyCollection`1<System.String>)'.
   at RazorInteractive.RazorKernelExtension.OnLoadAsync(Kernel kernel)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at RazorInteractive.RazorKernelExtension.OnLoadAsync(Kernel kernel)
   at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromAssembly(FileInfo assemblyFile, Kernel kernel, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 132
```
![image](https://user-images.githubusercontent.com/3438644/191191401-620cb53a-c6aa-4614-a34b-bba2d9585a90.png)

.NET Interactive Notebooks vscode-extension is `v1.0.3452020` (latest presently)

dotnet 6 SDK 
```powershell
❯ winget list dotnet.sdk.6
Name                             Id                     Version Source
-----------------------------------------------------------------------
Microsoft .NET SDK 6.0.401 (x64) Microsoft.DotNet.SDK.6 6.0.401 winget
```

**Comment by ekennedy6334** [comment]
I'm running into the same issue. However sometimes it doesn't report a failure. But then 
![image](https://user-images.githubusercontent.com/4388035/201552987-ae03bf4e-26ca-4067-963e-c2427b060e29.png)

**Comment by plbonneville** [comment]
Could you please give it a try with the updated version (1.1.0) that now uses .NET 7.0?

**Comment by mickut** [comment]
Both loading and running a Razor code-block works with VS Code 1.74.2 and .NET SDK 7.0.100
